spring:
  datasource:
    username: root
    password: 4789516729Chen..
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/maogay?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
